updated priya info
EmpMetCogLin/EmpMetCogLin.github.io pull request #2
Opened 2019-11-18 09:44 UTC by priyasilverstein

2019-11-18 16:50 UTC, Remi-Gau requested changes
One additional thing you might want to add. :-p

2019-11-18 16:50 UTC, Remi-Gau commented on _config.yml
>    position: TEST
@priyasilverstein Do you want to add that you are doing a post-doc at the moment in front of the position section?

2019-11-18 18:32 UTC, priyasilverstein commented
Oooh good idea hehe sorry, will do when I’m avec laptop

> On 18 Nov 2019, at 16:50, Remi Gau <notifications@github.com> wrote:
> 
> ﻿
> @Remi-Gau requested changes on this pull request.
> 
> One additional thing you might want to add. :-p
> 
> In _config.yml:
> 
> > @@ -38,11 +38,11 @@ people:
>    position: TEST
> @priyasilverstein Do you want to add that you are doing a post-doc at the moment in front of the position section?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2019-11-19 13:51 UTC, Remi-Gau reviewed
LGTM: Looks good to me

2019-11-19 13:52 UTC, Remi-Gau approved these changes

2019-11-19 13:53 UTC, merged